### ISSUE TITLE
Unable to record gifs anymore

### ISSUE THREAD

**Issue by carlosperate** [Gifox/Tracker#110]
I always get this error:

<img width="300" alt="image" src="https://user-images.githubusercontent.com/4189262/64337694-cc0f8c00-cfd7-11e9-8470-e651f0f48ad9.png">

System:
```
GPU_MODELS = Intel Iris Plus Graphics 655; 
FREE_DISK_SPACE = 34353.84 MB
OS_VERSION = 10.14.5
MACHINE_MODEL = MacBookPro15,2
RAM_SIZE = 16384
CPU_TYPE = Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
CPU_SPEED = 2700
CPU_COUNT = 4
CPU_64BIT = YES
LANGUAGE = en-GB
```

Not sure if there is any personal information in the log or settings, so instead of posting them here I'll send those in a normal in-app report as well.

**Comment by ianbytchek** [comment]
This may happen sometimes, but definitely not always. Relaunching the Gifox should help in most cases. But if not, please do send the in-app report, as the logs would contain hints. 

Also, you can try the [Gifox 2 beta](https://gifox.io/prerelease) where this issue is very unlikely to happen. There's an issue with the current build, please check [this](https://github.com/gifox/tracker/issues/108#issuecomment-500960163) out for the solution first.

**Comment by carlosperate** [comment]
I sent the report around the same time the issue was posted. This happens every time in my system. Before today I tried a couple of weeks ago and had the same issue, so it looks like a permanent problem in my system.
Currently using 2.0.0-beta.3, I'll try the steps listed in that ticket, looks promising!

**Comment by carlosperate** [comment]
Yep, this solution worked https://github.com/gifox/tracker/issues/108#issuecomment-500960163 🎉
