### ISSUE TITLE
Window shadow & background not working

### ISSUE THREAD

**Issue by lauriejim** [Gifox/Tracker#112]
Hello! I reporting an issue.

**Information**
- **Gifox version**: 1.6.1 03
- **OS**: MacOS Mojave 10.14.6

**The issue description**
When I active the `Window shadow` or the `Background` option, these options not work.

The `Window shadow` option adds a white space around the recorded screen but without the shadow.

And the `Backgroud` option do nothing more.

**Comment by ianbytchek** [comment]
Hey @lauriejim, apologies for the lag. That's strange, there was another similar issue and they both were put on hold, now, after looking at it closer the other one turned out to be something completely different. So, I just checked this in the latest version and it appears fine, but as far as I can remember nothing changed in that area + it was overall pretty stable. Could you check the latest version once more and we'll take it from there?

![2019-12-14 13 44 28](https://user-images.githubusercontent.com/1086845/70849569-17a7c080-1e78-11ea-9dc2-d7d4a155a303.gif)

**Comment by ianbytchek** [comment]
Actually, the other issue wasn't completely unrelated. I'll review everything else once more and will update you.

**Comment by ianbytchek** [comment]
After looking into this further the small inconsistencies turned out to be related to changes brought with new mouse and keyboard capturing that were introduced in version 2. As the result, changing window shadow capturing in quick configuration would take effect only in the next recording – this will be fixed in 2.0.3 release. We hope to provide a maintenance update for version 1 at some point when remaining issues with version 2 get fully ironed out but it's at the end of the backlog, so I'm gonna close this for now.
