### ISSUE TITLE
[Feature Request] Ability to give a title immediately before / after recording a GIF

### ISSUE THREAD

**Issue by robinmaben** [Gifox/Tracker#138]
### Problem -
While I understand the value of having timestamps as filenames, I find very cumbersome to recall what I was trying to convey. Re-watching previously recorded GIFs gets even more tedious when I need to **differentiate between several recordings** from the same day / hour.

### Proposed solution -
Brings up a tiny window to enter a title after a recording is done. This can be an opt-in setting if it's not useful universally. As a nice to have, there can be an additional setting to change this to prompt for a title prior to the recording.

### Quick hack - 
Bring up the file in a Finder window, pre-selected such that I can hit the `Return` key and give it a title.

### Future scope - 
More annotations on the recording 😉

**Comment by ianbytchek** [comment]
Hey @robinmaben, thanks for the feature request. Yes, this has been a long time coming and I've just looked into how this can fit nicely into the existing UI and thought to ask for suggestions.

Ideally we'll keep things as simple as possible and allow renaming recordings in the library view. This would apply to existing ones and ones in-progress. The way we wanted to do this initially is by clicking on title and making it editable. However, there's a problem, we already show the recording toolbar when user rolls over it:

![image](https://user-images.githubusercontent.com/1086845/77533905-aa042b00-6e8f-11ea-91a5-ea41754428b0.png)

So, instead, we're thinking to make the more (ellipsis) button act as the toolbar toggle button with the universal state. So, if you click it, toolbar will show up and stay visible/hidden, depending on the state. This way you won't need to click it every time to access the quick actions.

We'll make the title clickable to take you straight to the GIF and when you roll over it will show the rename button. If it doesn't feel too cluttered, will also add additional GIF info and controls.

This sounds like a neat approach, but if you guys have other ideas and know apps with similar layout that handle these situations well, please share your thoughts and references!

**Comment by Sayvai** [comment]
@ianbytchek when the recording toolbar shows on hover, why don't you shift the title to the top-side of the row, and then when the cursor further hovers over the title, show a rename / pencil icon to the right of the filename? 🤔

I also noticed that whenever i have to rename my GIFs, i just go into the desktop, and rename there, and the problem is that after renaming, and then proceeding to click on the Gifox icon from the menu bar, the GIF is no longer referenced in the list..

App Tier Status: **Purchased**

**Comment by ianbytchek** [comment]
This was the original idea, the problem with it is that everything starts to look clumsy. Though, the renaming is not available yet, everything looks very neat and simple – that's how we want things to stay. At the same time, yes, we are inclining towards making the states / views unified, so, on rollover we would have both the toolbar and editable title. In theory it should work, but I haven't had a chance to play with that yet.

The manual renaming behavior is annoying but expected. Originally, before introducing the editor, we'd simply remove the recording when the file would get deleted. Now we keep the recording in case the deletion was not intentional as the operation is irreversible. I will see if we can catch the file rename somehow and sync it with the app's info as it would still be useful in the future, once we introduce the in-app renaming.

**Comment by ianbytchek** [comment]
So, we've been experimenting with this and have a little prototype. Tt would be great to get more thoughts on it. What we want is to keep both the title and the toolset instantly accessible without adding additional gestures and re-educating users how to get from one place to another. We came up with this fluid UI, it's still a little clumsy but seems like something that might work. What do you think?

![2020-08-08 09 54 28](https://user-images.githubusercontent.com/1086845/89706512-538b1b00-d95e-11ea-8f34-258aad7aea7d.gif)

**Comment by Sayvai** [comment]
The UX on the prototype appears pretty slick / smooth. I like it.

So then how would the filename rename action work? Move cursor over the filename, a light border over the text appears to indicate that it's editable within the list items itself?

**Comment by ianbytchek** [comment]
Yes, something like that. As far as it stays accessible to the mouse and doesn't get covered we can do pretty much anything with it.

**Comment by iby** [comment]
Hey folks! I'm tidying up some old issues and this somehow slipped through my fingers – this was by far one of my favourite ones! 😅

Just wanted to let know that we've added support to rename stuff in progress a few releases ago, sorry for not notifying here earlier. Hopefully you already figured it out.

I just realized there's a small annoyance when the entire filename gets selected and we'd want it to act more like finder, i.e., not select the extension. Added this on the internal to-do and going to close this one down. If you have any comments or feedback or concerns, please feel free to reopen.

Again, thanks all for input and constructive feedback! 👍

![2022-06-18 12 49 33](https://user-images.githubusercontent.com/1086845/174436312-cc42fca0-f2bf-42cb-8b0e-5119e98bad14.gif)

**Comment by robinmaben** [comment]
That’s great news, thanks. Kudos to the team!

**Comment by robinmaben** [comment]
Hi,

Can I please transfer my license to another email ID? ***@***.***

**Comment by iby** [comment]
@robinmaben please drop us a line directly to our [support email](mailto:team@gifox.app) and we'll help take care of that.
