### ISSUE TITLE
Select Area Using Area Mode On Second Monitor Crashes

### ISSUE THREAD

**Issue by chadalen** [Gifox/Tracker#139]
**Problem:**
On a second monitor if you use Area Mode and select your entire window e.g select top left of your monitor then drag to bottom right of monitor GiFox will crash.

The issue seems to only happen on a second monitor and when making the area of recording big (take up the entire monitor screen)

**Expected:**
I should be able to use area mode on a second monitor and make the area of recording as big as possible.

**Steps to reproduce**
1. On a second monitor type hotkey ⌘ + ⇧ + 6 to select an area to record
2. On the second monitor start at the top left of the monitor then drag the area of recording to the bottom right of the second monitor. It should crash when your cursor is almost positioned at the bottom right of the screen.

**Notes:**
My second monitor is positioned to the right of my first monitor
![image](https://user-images.githubusercontent.com/12568665/76794290-adfbc300-6794-11ea-939f-5ea83a4dd983.png)
Second monitor resolution 1920x1080p
OS: MacOS (Catalina 10.15.3)
Computer: 2015 15" Macbook Pro
Graphics Card: AMD Radeon R9 M370X 2GB Graphics Card

**Comment by ianbytchek** [comment]
@chadalen You're a legend for filing this detailed report! This issue has been hunting us since version 2 came out but we were unable establish the exact cause. It is definitely related to a specific hardware set up but unfortunately this isn't reproducible just on any machine with an external screen, for example, we've tested this with a 3840x1600 display and never got caught this crash. So, we need to work backwards from the crash and try to guess what's causing it. Could you please provide additional info:

1. Make sure you've got the latest version (2.1.2).
2. When it crashes, please make sure to submit the crash log and send us another message using the in-app contact form to include the logs so we can cross-reference the crash report.
3. Since this definitely occurs on your machine, can you investigate further what and how causes the crash? Here's what comes to mind:
   a. Does it crash solid every single time you do that?
   b. Does this happen only when making selection from top-left to bottom-right or in other directions too?
   b. Does this occur when selection gets beyond certain size or is it related when it gets close to a particular edge of the screen? If second, can you roughly estimate the spacing to the edge?
   c. Does is occur with only this particular screen arrangement? E.g., if you align both on the bottom line or move main screen to the right?

👍

**Comment by chadalen** [comment]
1. ✅ I have the latest version
2.
✅ I submitted crash log
✅ I sent you an email with the in-app form and included logs
3.
a. Yes crashes 100% of the time.
b. Yes it does
It seems like it crashes every time I make the area larger than > 1800 x 1060
c.
I put the second monitor on the left side of the main monitor crashes
I put the second monitor above the main monitor crashes
I put the second monitor below the main monitor it crashes
Doesn't seem to be how the second monitor is arranged any arrangement will crash.

Might be helpful but my second monitor is a Lenovo L2364A

**Comment by ianbytchek** [comment]
Thanks Chad, that's great! I went through logs and will be honest, this is more of a mystery than before. Though I have a detailed crash log, the error occurs somewhere inside Apple's framework and contains zero information about what's causing this. I have a few wild theories and ideas where to look next, but before I do, can I ask to do a few more checks?

It seems to be definitely related to the selection size. It would be great to establish if this is more of a UI-related issue or whether it's caused by interactions. The selector mechanism and tracking are pretty complex, while there's nothing specific that causes the crash, there's more than one area where it might be originating.

1. Start new area selection of a safe size, say, 1700×1000. Using mouse, drag the right handle edge to increase selecting width beyond 1800, will it crash? Try the same with bottom handle to increase the height beyond 1060. The same with bottom-right handle to increase overall size.
2. Start new area selection of a safe size and try expanding it with keyboard, see [shortcuts and example](https://github.com/Gifox/Tracker/issues/55#issuecomment-414438894). Does it crash when resizing the area this way? If so, is it still the same canvas 1800×1060 + 1 pixel either direction?
3. Can you check if window selection causes the same crash? I'm assuming windows smaller 1800×1060 won't result in a crash, but anything larger would?
4. If no. 3 doesn't lead to a crash, can you pre-select a large window and convert the selection with <kbd>⌘ Cmd</kbd> + <kbd>⇧ Shift</kbd> + <kbd>6</kbd> shortcut into area, would it crash then?

If this is caused by UI, I expect the crash to occur while using either area scaling method, mouse and keyboard, plus it should crash when pre-selecting a large window. In this case we can tweak code and see if something works better. Otherwise I'll need to get back to Apple with findings and hopefully they can shed light into what might be the reason behind this all. Thanks again Chad!

**Comment by chadalen** [comment]
@ianbytchek So I tried to do 1-4 on my personal laptop which is a 2019 15" model and this doesn't happen. 

I tried this on my work's laptop which is a 2015 15" model and this happens 100% of the time. I tried to do this without a second monitor and it still happens. So I think this issue isn't related to a second monitor.

Both are running macOS Catalina version: 10.15.3

To answer your questions tested on my work laptop (2015 15" Macbook)

On primary monitor crashes past 1425 x 900 or 1440 x 875.
1. 
> Start new area selection of a safe size, say, 1700×1000. Using mouse, drag the right handle edge to increase selecting width beyond 1800, will it crash? 
Yes crashes at 1900 x 1000

> Try the same with bottom handle to increase the height beyond 1060.
Crashes at 1700 x 1060 

2.
> Start new area selection of a safe size and try expanding it with keyboard, see shortcuts and example. Does it crash when resizing the area this way?

Yes it does

> If so, is it still the same canvas 1800×1060 + 1 pixel either direction?
Yes same dimension

3. 
> Can you check if window selection causes the same crash? I'm assuming windows smaller 1800×1060 won't result in a crash, but anything larger would?

Window selection doesn't crash and the window selection I used was larger than 1800x1060

4. 
> If no. 3 doesn't lead to a crash, can you pre-select a large window and convert the selection with ⌘ Cmd + ⇧ Shift + 6 shortcut into area, would it crash then?

I pre-selected a large window, tried resizing it and it crashed.

**Comment by ianbytchek** [comment]
@chadalen This is fantastic info, thank you! Yes, my initial feeling was that this is GPU-related. Now that you say that the crash occurs strictly past the specific size and using any sizing method this verifies that the issue is with the UI, which is GPU-managed.

I'll digest this and will see if there's anything interesting that can be tweaked to avoid this. 

No. 4 really isolates this case making things a lot easier. There are two differences between two selection modes: resizing handles and dash-animation, they aren't present in the window-selection mode, but are present in the area-selection mode. 

You say `tried resizing it`, can I just confirm the last thing. Does it crash when you actually convert window into area selection with the shortcut or when trying to resize the converted selection? This is the important part! :)

**Comment by chadalen** [comment]
@ianbytchek It crashes when trying to resize the converted selection not when converting the window into area selection.

**Comment by ianbytchek** [comment]
That's not good… 😅 Okay, thanks for the input @chadalen. We've been talking about this issue with Apple a few weeks ago, but with this information they might come to new conclusions. I'll communicate and post updates here. In the meanwhile I'll look if there's anything in our code that might be changed, but the fact that the crash is actually event related makes this tricky. In any case, I'll keep you posted here. Bear with us!

**Comment by ianbytchek** [comment]
Just to give the heads, we're still waiting to hear from Apple on this, so, no progress yet, but hoping to hear back something this week.

Also, a very lame workaround idea. Since the crash occurs during resizing, you probably can try to have any window of roughly the same size the area you need to capture, get it selected with window mode and convert it into area selection, then <kbd>Cmd</kbd> + <kbd>Tab</kbd> to switch the window. Can also try <kbd>Cmd</kbd> + <kbd>A</kbd> to select the whole screen, but it will probably also cause the crash.

**Comment by FVI812** [comment]
@chadalen same here bro, I got u. @ianbytchek got at email from me recently when I reported the same crash and it happens also with just ONE monitor/screen on my mac book pro, meaning no secondary displays although I also use 98% of the time my iPad as a second screen with Duet Display, hope Apple helps us all out soon. Stay safe these days fellas.

**Comment by FVI812** [comment]
Hey guys, I made the latest updates just now.....both Gifox to 2.1.3 and Mac OS  10.15.4.

The crash remains. Both second display (using Duet Display) or just my main MBP screen when activating the Area Mode, starting with the pointer at my up-left display corner till the the bottom right corner, before reaching that final corner, boom.....it closes but the crash window identifier (the one it appeared automatically by opening again Gifox) no longer appears.

FYI Fellas...... bug/issue persists.

**Comment by ianbytchek** [comment]
Thanks for keeping an eye on this. We're still waiting to hear back from Apple and it might take awhile – they are talking internally with teams who worked on the crashing code and relaying the info back to us. I know that the answer isn't really helping, but without us being able to reproduce this locally we can't do anything without your feedback – you are literally hands and eyes here. 

With @chadalen's feedback we roughly know what part of the app is related to the crash. If you can help with the testing we can try to isolate this further and tweak some code in hope something will fix this – we'd put together custom builds and will need you to test and send back logs. Let me know if you're up for this? Would be great if you use Telegram, please [ping me](https://t.me/ianbytchek) if you do.

@chadalen Are you using Duet Display by any chance?

**Comment by chadalen** [comment]
@FVI812 Just wondering but what year is your Macbook?

@ianbytchek Well hopefully Apple gets back to you. I honestly think it's an issue with the 2015 Macbook graphics card. I've used Gifox on 3 work computers they are all 2015 models and Gifox crashes on all of them. I've tried a 2018 Macbook pro had no problems. I've also tried a 2019 Macbook pro and have had no problems. All using Mac OS Catalina as well.

I'm not using a Duet Display. I've unplugged the second monitor and Gifox still crashes.

**Comment by ianbytchek** [comment]
This happens mostly on 2012-2018 models, most often 2015 and 2018 models, and only on Catalina. I haven't seen a single crash yet on 2019 machine nor on pre-Catalina macOS. I'm assuming this happens only on dual-GPU architectures. Is that the case with you @chadalen, the AMD Radeon R9 M370X is the discrete GPU, correct? Can you share your GPU model @FVI812?

<details><summary>Here's a device sample from diagnostics…</summary>

&nbsp;  
- MacBook Pro 13" (Retina, Mid-2017), macOS 10.15.3, 1d ago
- MacBook Pro 15" (Retina, Touch, Mid-2017), macOS 10.15.4, 1d ago
- MacBook Air 13" (Early-2015), macOS 10.15.0, 2d ago
- MacBook Pro 15" (Retina, Touch, Late-2016, B), macOS 10.15.2, 3d ago
- MacBook Pro 15" (Retina, Touch, Late-2016, B), macOS 10.15.2, 3d ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3d ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3d ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3d ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.4, 3d ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.4, 3d ago
- MacBook Air 13" (Early-2015), macOS 10.15.3, 3d ago
- MacBook 12" (Mid-2017), macOS 10.15.4, 3d ago
- MacBook 12" (Mid-2017), macOS 10.15.4, 3d ago
- MacBook 12" (Mid-2017), macOS 10.15.4, 3d ago
- MacBook 12" (Mid-2017), macOS 10.15.4, 3d ago
- MacBook Air 13" (Early-2015), macOS 10.15.0, 4d ago
- MacBook Pro 13" (Retina, Late-2016), macOS 10.15.3, 4d ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 4d ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 4d ago
- MacBook 12" (Mid-2017), macOS 10.15.4, 4d ago
- MacBook 12" (Mid-2017), macOS 10.15.4, 4d ago
- MacBook 12" (Mid-2017), macOS 10.15.4, 4d ago
- MacBook Pro 15" (Retina, Touch, Late-2016, B), macOS 10.15.3, 4d ago
- MacBook Pro 15" (Retina, Touch, Late-2016, B), macOS 10.15.3, 4d ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 5d ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 5d ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 5d ago
- MacBook Pro 13" (Retina, Early-2015), macOS 10.15.3, 6d ago
- MacBook Pro 13" (Retina, Mid-2017), macOS 10.15.3, 6d ago
- MacBook Pro 15" (Retina, Touch, Mid-2017), macOS 10.15.3, 6d ago
- MacBook Air 13" (Early-2015), macOS 10.15.0, 6d ago
- MacBook Pro 13" (Retina, Early-2015), macOS 10.15.3, 6d ago
- MacBook Pro 15" (Retina, Touch, Late-2016, B), macOS 10.15.3, 6d ago
- MacBook Pro 15" (Retina, Touch, Late-2016, B), macOS 10.15.3, 6d ago
- MacBook Air 13" (Late 2018), macOS 10.15.3, 1w ago
- MacBook Air 13" (Late 2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 13" (Retina, Late-2016), macOS 10.15.4, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Late-2013, A), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Late-2013, A), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Late-2013, A), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Late-2016, B), macOS 10.15.3, 1w ago
- MacBook Pro 13" (Retina, Late-2012), macOS 10.15.4, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Retina, Mid-2017), macOS 10.15.3, 1w ago
- MacBook Pro 13" (Retina, Mid-2017), macOS 10.15.3, 1w ago
- MacBook Pro 13" (Retina, Late-2012), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Retina, Late-2012), macOS 10.15.4, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 1w ago
- MacBook Air 13" (Early-2015), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Retina, Mid-2017), macOS 10.15.3, 1w ago
- MacBook Pro 13" (Retina, Touch, Mid-2017), macOS 10.15.3, 1w ago
- MacBook Pro 13" (Retina, Late-2012), macOS 10.15.4, 1w ago
- MacBook Air 13" (Early-2015), macOS 10.15.0, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 1w ago
- MacBook Pro 13" (Retina, Mid-2017), macOS 10.15.3, 1w ago
- MacBook Pro 13" (Retina, Mid-2017), macOS 10.15.3, 1w ago
- MacBook Pro 13" (Retina, Late-2016), macOS 10.15.3, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.2, 1w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.1, 1w ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Retina, Mid-2017), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 1w ago
- MacBook Pro 13" (Mid-2012), macOS 10.15.4, 1w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 1w ago
- MacBook Air 13" (Mid-2013), macOS 10.15.1, 1w ago
- Mac mini (2018), macOS 10.15.3, 2w ago
- Mac mini (2018), macOS 10.15.3, 2w ago
- Mac mini (2018), macOS 10.15.3, 2w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.2, 2w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.2, 2w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.2, 2w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 2w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 2w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 2w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 2w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.14.6, 2w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.2, 2w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.2, 2w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 2w ago
- Mac mini Server (Late-2012), macOS 10.15.3, 2w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 2w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 2w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 2w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 13" (Retina, Late-2013), macOS 10.15.3, 3w ago
- MacBook Pro 13" (Retina, Late-2013), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 13" (Retina, Mid-2017), macOS 10.15.3, 3w ago
- MacBook Pro 13" (Retina, Mid-2017), macOS 10.15.3, 3w ago
- MacBook Pro 13" (Retina, Touch, Late-2016, A), macOS 10.15.3, 3w ago
- MacBook Pro 13" (Retina, Touch, Late-2016, A), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.4, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.4, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.4, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.4, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.1, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.1, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.2, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Touch, Mid-2018), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 15" (Retina, Mid-2015, B), macOS 10.15.3, 3w ago
- MacBook Pro 13" (Retina, Mid-2017), macOS 10.15.3, 3w ago
- MacBook Air 13" (Mid-2013), macOS 10.15.2, 3w ago
- iMac 27" (5K, Mid-2017), macOS 10.15.3, 3w ago
- iMac 27" (5K, Mid-2017), macOS 10.15.3, 3w ago
- iMac 27" (5K, Mid-2017), macOS 10.15.3, 3w ago
- iMac 27" (5K, Mid-2017), macOS 10.15.3, 3w ago

</details>

P.S. I myself on MacBook Pro (Retina, 15-inch, Mid 2015) model but it's Intel Iris Pro 1536 MB GPU, which is a real problem, because there are a few other troubles with multi-GPU architectures and I can't properly debug them on the work machine.

**Comment by chadalen** [comment]
@ianbytchek The AMD Radeon R9 M370X is the graphics card the 2015 Macbook Pro has built inside of it. I'm not using any other graphics card.

**Comment by FVI812** [comment]
Hey Guys,

Sorry for the delay, here is the tech specs of my MBP......it seems older models are the ones presenting the issue from what I just read on all of this thread. Anyways, let's hope it get's fixed as well.

Hope everyone is ok, stay safe.
![2020-04-10 22 22 26](https://user-images.githubusercontent.com/20651319/79034182-d00d1900-7b79-11ea-9728-b39575162686.jpg)
![2020-04-10 22 22 38](https://user-images.githubusercontent.com/20651319/79034183-d0a5af80-7b79-11ea-8187-0b63ca0df504.jpg)

**Comment by ianbytchek** [comment]
Friends, Gifox 2.2.0 Beta was just published, please give it a try – make sure to enable prerelease updates in general preferences. Thanks for all your input here and on Telegram, it really wouldn't be possible without all your help! 

The issue comes with a change in the view auto-layout handling on macOS Catalina, which, in very certain situations, sends UI redrawing into recursion and crashes the process. We've reworked the UI parts that were affected by that and notified Apple, so hopefully will have some answers on WTF was really happening behind the scenes.

There are also other improvements and fixes in 2.2.0. Please give it a try and confirm that there are no regressions. The next public release is going to be awesome! 👍
