### ISSUE TITLE
Imgur Social Login not working

### ISSUE THREAD

**Issue by sir-zellot** [Gifox/Tracker#142]
Hi! I noticed that the social login with imgur is not working.

When I try to signin in imgur with my Google account in the popup browser 
then I accept the cookie banner
then i click on the Google icon / Facebook icon / Twitter icon / Yahoo

no response
![image](https://user-images.githubusercontent.com/12135320/77170903-01834f00-6abc-11ea-98fc-1758484c6cbb.png)

**Comment by ianbytchek** [comment]
I'm afraid you can authorize into Imgur only using username/email + password. We spoke with Imgur about this awhile ago but couldn't find a way around this. In the nutshell, because of the way OAuth protocol works this becomes OAuth within OAuth and rather tricky to workaround inside non-standard browser.

We're planning to start working shortly on the new integration and sharing system, where we will reevaluate how Gifox integrates with other services, so hopefully will find a better solution then.
