### ISSUE TITLE
Filesize is bigger than equivalent QuickTime video

### ISSUE THREAD

**Issue by KoltonG** [Gifox/Tracker#143]
# Issue
I've recently created a short video clip by accident using the new Mac **cmd+shift+5** command and found that the file size for this QT video was ~800kb when the equivalent video on Gifox was ~2.5MB.

I was wondering if there is a way to get the file sizes to be smaller than a QT video as this was a big reason to use Gifox!

Somewhat related to #105 

# Resources
### Gifox Output - 2.5MB
![2020-03-25 09 26 37](https://user-images.githubusercontent.com/3606121/77536660-728b8380-6e7b-11ea-8e17-9459a9c2a031.gif)

### Quicktime Output (must be unzipped) ~ 800kb
[Screen Recording 2020-03-25 at 9.22.02 AM.zip](https://github.com/Gifox/Tracker/files/4380845/Screen.Recording.2020-03-25.at.9.22.02.AM.zip)

**Comment by haakonstorm** [comment]
# Reasons for differing file sizes

- The GIF animation format is inherently ineffective in every way. Compared to modern video compression codecs, regarding file size and efficiency; a compressed video will end up smaller and better looking every time, variables like frame rate and resolution kept identical.

- That said, everybody loves GIFs because they are supported most everywhere including auto-play and looping.

- The usual tips applies: trim your clip (cut from beginning and end) to make is as small as possible. Reduce motion (if you make a video yourself, use a tripod/static camera). Reduce the amount of colors. Have static, mono-colored backgrounds.

# Online services for reducing GIF animation size

[EZGif](ezgif.com)
[GIF Compressor](gifcompressor.com)

# Use Photoshop to work with GIFs

[GIFt export](https://graphicriver.net/item/gift-export/14768785?_ga=2.190973418.1543439782.1585408463-378992761.1585408463)

# From the command line

Use `Gifsicle`. Extremely versatile tool (especially now that `giflossy` has been merged with upstream `gifsicle`) and easy to use. [Gifsicle on GitHib](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&cad=rja&uact=8&ved=2ahUKEwjGzJ_-vL3oAhVqsYsKHeFADGkQFjACegQIBBAB&url=https%3A%2F%2Fgithub.com%2Fkohler%2Fgifsicle&usg=AOvVaw28l6LUUHuaXe2vXUGbYTXs)

Using Gifsicle to reduce size of existing GIF, example:
`./gifsicle -O3 --lossy=80 -o lossy-compressed.gif input.gif`

`gifox` has a super nice UI and interface and UX. IMHO, KISS, let `gifox` do what its good at and let it become even better at it, and offload the rest to existing tools that is already better at those things. By combining `gifox` with `gifsicle`, for example using `Folder Actions` in macOS, using `Hazel` for automating `gifox'`s output folders, you can automate your lossy and/or lossless compressions/transcodings of your video/GIF recordings.

**Comment by ianbytchek** [comment]
@haakonstorm Wow, thanks for the great write up! Very practical advices, I can only add [ImageOptim](https://imageoptim.com/mac) doing extra optimization right on your Mac, though you can achieve pretty much the same result with just fine tuning your export options.

@KoltonG It's true what @haakonstorm says, though, it is a two way road – GIF still can be unbeatable for certain animations and completely suck for others.

First, we have a great article on [Mastering High Quality GIFs with Gifox](https://medium.com/gifox/mastering-high-quality-gifs-with-gifox-e08647cd5b3b) talking about ins and outs of compression – this is the best place to start.

Now, two factors affecting file size the most are resolution size and amount of animation you have between the frames, when file size is critical, aim at the following.

1. Reduce the motion, especially transitional animations, to a minimum. The app uses frame diffing technique by encoding only changed frame area. If you have any animations covering large areas (like a camera recording, fade animations, window or large object movements, **specially scrolling**, etc) the diffing won't be of much help.
2. Consider downscaling the exported GIF. You can configure this in the recording settings or globally before creating the recording. Either fit it to a specific size or scale it down by 2 or 4 (best for sharper antialiasing).
3. Consider using plain color backgrounds, especially when motion is done over complex images, e.g., dragging a window over the macOS desktop image.
4. If there isn't many gradient colors try completely disabling dithering.

Downscaling is the best place to begin with. GIF encodes colors in a funny way and just depending on the color distribution in the image you can get two completely different results size-wise. That includes even black and white GIFs, so, low colors doesn't necessarily guaranty a tiny file size.

In your case I think the best way to achieve smaller file size is to use the lower recording frame rate. You can analyze your GIF with `exiftool -v my.gif` command and if I'm getting my math right you used >=50 fps based on `0.02 s` delays between frames. It makes the output much smoother, but with everything else factored in 2.5 MB is the price to pay.

Using [gifsicle](https://graphicdesign.stackexchange.com/a/20937/54327) to drop frames from your existing GIF:

```sh
gifsicle -U tst.gif -d 2 `seq -f "#%g" 0 1 107` -O3 -o out-drop-0.gif
```
[out-drop-0.gif](https://user-images.githubusercontent.com/1086845/77832604-38e2a300-712f-11ea-8ce2-3edeba035ba8.gif), 2.5 MB – control, no dropped frames

```sh
gifsicle -U tst.gif -d 4 `seq -f "#%g" 0 2 107` -O3 -o out-drop-1.gif
```
[out-drop-1.gif](https://user-images.githubusercontent.com/1086845/77832608-41d37480-712f-11ea-94c2-eb5515f40bd7.gif), 1.4 MB – dropped every other frame

```sh
gifsicle -U tst.gif -d 6 `seq -f "#%g" 0 3 107` -O3 -o out-drop-2.gif
```
[out-drop-2.gif](https://user-images.githubusercontent.com/1086845/77832610-4304a180-712f-11ea-89f3-14d3b9adb456.gif), 981 KB – dropped every 2 frames

```sh
gifsicle -U tst.gif -d 8 `seq -f "#%g" 0 4 107` -O3 -o out-drop-3.gif
```
[out-drop-3.gif](https://user-images.githubusercontent.com/1086845/77832612-4435ce80-712f-11ea-8f39-1d5d2c943ad4.gif), 760 KB – dropped every 3 frames

As you can see, the file size drops down almost linearly and you barely start noticing low frame rate when dropping every 3 frames.

With all that said, Gifox currently cannot do frame dropping but this on the list of coming soon features. There's also issues #136 where the initial export might be playing faster, which is fixed in the upcoming release, in the meanwhile, just reexport from the editor.

**Comment by KoltonG** [comment]
Amazing response @haakonstorm @ianbytchek 🎉  Thank you both for the epicly detailed information, I've learnt a lot reading this!
