### ISSUE TITLE
Long recordings never complete encoding and remain stuck in the list

### ISSUE THREAD

**Issue by gilbox** [Gifox/Tracker#147]
<img src="https://user-images.githubusercontent.com/2136203/80658940-595a9180-8a3c-11ea-838e-8d4adcd0fe86.png" width="300" />

I tried making a long recording of a console session. The final gif of this session would be quite small, possibly less than 1mb (based on shorter sessions that completed). However, the gif never completes encoding and remains stuck in my list with no way to remove it. BTW, in V1 we could delete/cancel an in-progress recording. In v2 we have to wait until it's done. Seems like a step backwards!

This bug consistently happens for long recording sessions.

**Comment by ianbytchek** [comment]
Hey Gil, thanks for reporting this. We're tracking this issue in #137, please see it for details and updates.

We're expecting to see this resolved in the latest 2.2.0 Beta. If you're not on it, please give it a try?

> BTW, in V1 we could delete/cancel an in-progress recording. In v2 we have to wait until it's done. Seems like a step backwards!

We moved towards gestures and standard keyboard actions to avoid cluttering the UI, though, I agree, it's not very obvious. We plan to have another go at the UI in 2.3.x releases, in the meantime you can use side-scroll to delete the recording or select it and press the delete key, see [here](https://medium.com/gifox/gifox-2-is-here-release-highlights-bc93e670388d#d530). However, if it's getting stuck, I'd quit the app and reopened it in order to try another export.

> The final gif of this session would be quite small, possibly less than 1mb (based on shorter sessions that completed).

If the export never completes then it's expected. However, I've been observing lately what possibly might be a Finder glitch, when the export completes the file size is suspiciously small, but if you try copy and paste the GIF the pasted file size would be different and the copied file size would update as well. Will need to look if there's something we can do at our end to prevent this from happening.

**Comment by gilbox** [comment]
> If the export never completes then it's expected.

No, I meant that for a gif that completed successfully it seems to have compressed it with excellent efficiency. Since I'm just recording a console window there's not a lot of colors or complex graphics happening.

**Comment by ianbytchek** [comment]
Yes, sometimes GIF is an absolute gold dust at that. We do frame diffing, so, if there's not much action on the screen, only a tiny portion of the graphic gets encoded making it super efficient! 🙂
