### ISSUE TITLE
Stop Recording shortcut hijacks Mac keys

### ISSUE THREAD

**Issue by MarceloPrado** [Gifox/Tracker#158]
It took me a huge amount of time to understand why my "Command + Enter" keyboard shortcut stopped working. This was really frustrating, as it's an essential part of a lot of apps (Postman, TablePlust, VSCode, etc).

I discovered an application called [ShortcutDetective](http://www.irradiatedsoftware.com/downloads/?file=ShortcutDetective.zip) that tracks which app is using a shortcut. I was able to track GiFox as the one using the "Command + Enter" keys. I set the "Command + Enter" to easily stop my recordings, but it seems it's being captured by GiFox even when no recording selector is opened. 

![Screenshot 2020-06-18 14 50 58](https://user-images.githubusercontent.com/8047841/85055655-43339c80-b174-11ea-8a82-6dc7f305dff4.png)

After I removed this binding from GiFox, the shortcut started working again.

Not sure if this helps, but I'm on Catalina 10.15.4.
Thanks!

**Comment by ianbytchek** [comment]
That's a good point, thanks for bringing this up! Should be fixed in the upcoming release.

**Comment by ianbytchek** [comment]
This is fixed in the latest 2.2.1 release – the stop recording shortcut will get activated only during the recording. 

Note to future self: Because the shortcut doesn't get registered immediately after the app launch there's no info on whether it conflicts with any other bindings until the recording starts. This doesn't change anything on practice, but something to keep in mind if stops working.
