### ISSUE TITLE
Logfile growing rapidly to over 161 GB

### ISSUE THREAD

**Issue by krodak** [Gifox/Tracker#174]
I have a constant issue with logfile for Gifox 2. It quite quickly can take up to 160 GB of storage space.

Would appreciate update with not that many `print` to local storage.

<img width="1010" alt="CleanShot 2020-10-07 at 11 58 36@2x" src="https://user-images.githubusercontent.com/1955364/95317002-d6641f80-0894-11eb-98f1-b8cbabdbf416.png">

**Comment by ianbytchek** [comment]
Wow, insane! Thank you for reporting! It's supposed to get trimmed every now and then down to 1k lines. I just checked mine and it's only 120 KB with a little over 1k lines. To be honest, I'd be surprised to see it getting over a few hundred MB. 160 GB definitely indicates something is wrong.

Can I ask to send your diagnostics data using the in-app contact button, it should send the last 1000 lines, hopefully it will include some clues. If you still got the log or observe it getting beyond a few MB in size, can you try compressing it (or copying a large chunk into a separate file and also compressing it) and email it to team@gifox.io or use [WeTransfer](https://wetransfer.com) or something alike to send a link?

That would be of huge help. We'll try to make sure this gets fixed in the upcoming release once know what's causing this.

**Comment by krodak** [comment]
Unfortunately I needed to delete this one as it causes my system to freeze
during work. Will send a report next time it happens.

śr., 7 paź 2020 o 12:38 Ian Bytchek <notifications@github.com> napisał(a):

**Comment by ianbytchek** [comment]
@krodak Polite ping. Was wondering if you had a chance to observe this again?
