### ISSUE TITLE
Gifs turn out all black

### ISSUE THREAD

**Issue by rogierslag** [Gifox/Tracker#180]
Since a short while some of my gifs turn out as a completely black. I have no idea what happened (macOS update perhaps)?
![2020-10-27 18 17 37](https://user-images.githubusercontent.com/2778689/97337760-f9289900-1880-11eb-8ccc-f8985a892a5c.gif)

I did check the following:

1. Doesnt matter which screen (macbook or external) the recording is done
1. Dark mode doesnt influence the result either
1. Restarting sometimes fixes the issue 

Ironically the first frame is shown correctly in the gifox dropdown

<img width="348" alt="Screenshot 2020-10-27 at 18 22 27" src="https://user-images.githubusercontent.com/2778689/97338102-650b0180-1881-11eb-8527-35a9122b7184.png">

**Comment by ianbytchek** [comment]
@rogierslag Thanks for reporting this. Yes, unfortunately this is a different form of #159. We have a 2.2.5 Beta that hopefully makes things better, please enable pre-releases in general preferences and check for updates or get it directly from [here](https://distribution-absf.s3.eu-central-1.amazonaws.com/gifox/020205.00-beta.dmg). 

As you mentioned, this issue is supposed to be fixed with restarting the app but will likely to return in a few days/weeks of running the app without quitting it. If you do run into this again in the Beta, please include your diagnostic data as we're hoping it would contain some clues.

**Comment by hjemmel** [comment]
I am having the same problem in the final 225 version

**Comment by ianbytchek** [comment]
Thank you for input everyone! I'm closing this down as any remaining issues would be related to the mother of all issues #159 – please see it for the full background and the quick workaround for the time being remains restarting the app.

**Comment by austinbiggs** [comment]
This is also happening for me...

**Comment by pambram** [comment]
it happens for me too, in 2023... I can't use the product

**Comment by vandriesh** [comment]
for me worked removing privileges, than reenabling - I guess after os nad or app update something got blocked.
