### ISSUE TITLE
[Feature request] Native support for Apple Silicon / M1 devices

### ISSUE THREAD

**Issue by Kaspik** [Gifox/Tracker#186]
Hello!

First of all - thanks for this app, it made my life easier when recording "videos" for Github PRs before videos were supported.

I'm using MacBook Pro M1 for last two months - Gifox works correctly on it, but I was wondering what's the timeline/ETA on either Universal app (probably easier for you?) or Apple Silicon native app support.

I haven't seen any info about it on Twitter nor did I find anything here in Tracker, so opening this ticket for future reference.

Thanks, cheers!

**Comment by iby** [comment]
Hey Jakub, thank you for the compliments and the very relevant issue. We are road-blocked by two big libraries that we can't live without and waiting for them to get updated and natively support M1. Hopefully this happens in early February and we can release the new version. If not, we'll try to go the hard way around it and find an alternative workaround, but either way this is a pretty high priority. I'll post further updates here, stay tuned!

**Comment by Kaspik** [comment]
Hey! By any chance - what are these libraries? I built Universal app already and had to re-built some libraries as well already so I might help ya. :)

**Comment by iby** [comment]
Thanks for a helping hand! I believe we're mostly limited to FFmpeg right now. I've seen a few examples where the project gets compiled with a pretty heavy [build script](https://github.com/ssut/ffmpeg-on-apple-silicon/blob/7155e7a04c7002be511ee2bac8d97c29c91fc5a8/build.bash). We also use a custom build script and it would require a lot of work in order to merge the two. I was hoping to see an official release to avoid complicating the build logic further and reverting it when the arch support gets eventually added. There are also other priority tasks at hand, so there are plenty of things to do. However, if we see no progress in the coming week or two we'll go ahead with reworking our build pipeline to add the support.

**Comment by Kaspik** [comment]
Thanks for the info. The script seems to be similar to what can be found on https://www.osxexperts.net - but yeah, these things are always tricky.

Thanks for the heads up, we will keep looking forward. :)

**Comment by akrsnr** [comment]
> Thanks for a helping hand! I believe we're mostly limited to FFmpeg right now. I've seen a few examples where the project gets compiled with a pretty heavy [build script](https://github.com/ssut/ffmpeg-on-apple-silicon/blob/7155e7a04c7002be511ee2bac8d97c29c91fc5a8/build.bash). We also use a custom build script and it would require a lot of work in order to merge the two. I was hoping to see an official release to avoid complicating the build logic further and reverting it when the arch support gets eventually added. There are also other priority tasks at hand, so there are plenty of things to do. However, if we see no progress in the coming week or two we'll go ahead with reworking our build pipeline to add the support.

how many weeks have been? Is there any fitting process into M1s?

**Comment by iby** [comment]
Ooops, sorry friends, completely forgot to resolve the public ticket for this. The M1 support has been out for awhile now since v2.3.0. Everything runs smoothly on Apple Silicon. We have another update coming out in a few days with further improvements, stay tuned! ✌️
