### ISSUE TITLE
License update from Gifox 1 to 2

### ISSUE THREAD

**Issue by TonioGela** [Gifox/Tracker#193]
Is it possible to know how to upgrade the license? The site doesn't explicitly say a word about that.

**Comment by iby** [comment]
Hey @TonioGela, apologies for the lagged reply! The new website is in the build, so yes, sorry, the information is not very clear at the moment. It's available in the licensing dialog when you choose `Upgrade to Gifox Pro`.

There is a way to upgrade both App Store and direct-download versions. Upgrading the direct-download version can be done straight in the app, besides all users were sent upgrade instructions awhile back.

Upgrading the App Store version is a little more tricky and many users find it very clumsy: you need to get both, the old and the new version, installed in order to verify the purchase, but the App Store would replace one with another because they have the same name. 

1. If you already have Gifox 2 you'll need to rename it from Gifox to Gifox 2, otherwise you can rename the original version in the following step.
2. Get the original app from your [previous downloads](https://support.apple.com/en-us/HT201272#apps).
3. Launch Gifox 2 and follow upgrade instructions: you'll need to select the original version to get the discount.
3. If you renamed Gifox 2, it's best to quit it and rename it back to Gifox after the upgrade.

We would offer the same standard 35% upgrade discount for the direct-download version if you want to use that instead of the Mac App Store one – just send us the purchase confirmation / receipt. If you go with the direct-download make sure to remove all App Store Gifox copies and get the latest version from [our website](https://gifox.io). Direct-download also has the Beta channel and updates are typically published a day or two earlier, so it's a little better than the App Store version in that sense.

I hope that makes things a little clearer? Please let know if I can add any other details to that?

**Comment by TonioGela** [comment]
Thanks I didn't notice that the app was in fact offering a way to apply a discount code. Thanks!

**Comment by iby** [comment]
The Mac App Store version does offer the discount right in there. Inside the direct-download version you can only get the code inside the app or simply use a pre-filled checkout link. If you want to apply it manually you can do so on the final checkout slide under the payment buttons.
