### ISSUE TITLE
Stops Recording without pressing a shortcut

### ISSUE THREAD

**Issue by alexandravelez-ux-ui** [Gifox/Tracker#194]
https://screencast-o-matic.com/watch/crhteqVh6xp

In the middle of recording, Gifox is stopping the screen recording feature, 
without pressing any shortcuts or the escape button.

**Can you determine why it stops recording in the middle of a session?**

**Comment by iby** [comment]
That's a great issue report! Wish all of them were like that! 😀

This is the limitation of the free version. We show that in the welcome screen and it's available if you click on that flash orange button at the bottom of the library popover:

![image](https://user-images.githubusercontent.com/1086845/120420410-5d5e8e80-c375-11eb-9b23-a787cd855c82.png)

We are intentionally not bugging users with "please upgrade" messages because it can be very annoying. We're updating our website to make this clearer for users who're about to download the app. If you have any suggestions how to improve this, please share! 🙏

**Comment by alexandravelez-ux-ui** [comment]
I understand the intention is to not bug users with please upgrade messages, but there's no feedback mechanism to say "you've gone over your limit" or "free accounts have a 1 minute limit" in the recorder itself. 

For free accounts, consider having some kind of disclaimer/explanation in the product until they upgrade. I was totally unaware of the 1 minute limit. 

Frankly, it felt like Gifox was ending the recording in **15 seconds** or less. That's definitely less than 1 minute.
