### ISSUE TITLE
Cannot recover lost license

### ISSUE THREAD

**Issue by tkozMBAI** [Gifox/Tracker#230]
I got a new laptop and can't sign in to Gifox 2 Pro. I found my receipt, but couldn't find any email with a license number. Below is my proof of purchase.
![Screen Shot 2022-03-02 at 9 38 03 PM](https://user-images.githubusercontent.com/78038177/156485641-9a54d61f-d59b-493d-815f-369f315a5ab6.png)

I tried to go through my.paddle.com to retrieve it, but the error message below came up. I'm not sure what to take away from this... firewall issue maybe? Unfortunate UX either way!
![Screen Shot 2022-03-02 at 9 25 54 PM](https://user-images.githubusercontent.com/78038177/156485690-ec7a7d68-69a2-41d4-8189-ea7527533e33.png)

Hoping someone can help soon! Cheers
—Tasha

**Comment by santiagofm** [comment]
Hello! I'm facing the same issue... reinstalled macOS and now I cannot recover the license. I've got Apple's purchase confirmation email from Sep/2021 but did not get one from you guys.

**Comment by iby** [comment]
Sorry friends, we've been busier than the usual lately and this slipped through my fingers.

@tkozMBAI First, please make sure you're using the copy of the app from the Mac App Store, not the direct-download version – they use different licensing mechanism and not compatible with each other.

Second, yes, that Error 1015 looks like "security" bug on the Paddle side. Using a different network or VPN normally solves issues like that, but then again, you don't need to bother with them, just get the app from the website.

@santiagofm It also sounds like you need to download the app from the Mac App Store if you purchased it there. Due to customer privacy developers don't get notified by Apple about purchases or share customer details. Even if we wanted to we wouldn't be able to – this is probably not a bad thing from the customer perspective 😅

Let me know if you're having any troubles guys and again, sorry for the lagged response @tkozMBAI!

**Comment by tkozMBAI** [comment]
@iby Due to permissions and security issues, I cannot and have not downloaded any apps from the app store. My first purchase was a direct download, so I don't know why there would be a compatibility issue. Because I need Gifox for work, I ended up re-purchasing and downloading from the site directly, but honestly, I feel pretty ripped off right now.

**Comment by santiagofm** [comment]
> @santiagofm It also sounds like you need to download the app from the Mac App Store if you purchased it there. Due to customer privacy developers don't get notified by Apple about purchases or share customer details. Even if we wanted to we wouldn't be able to – this is probably not a bad thing from the customer perspective 😅

Worked like a charm! Perhaps it would be good to add this information to the license recovery view, if it isn't already there 😅 

Thanks!
