### ISSUE TITLE
Uploading media isn't possible

### ISSUE THREAD

**Issue by ColinRhoads** [Gifox/Tracker#242]
I'm trying to upload media by dragging and dropping from the Gifox dropdown in the native menu at the top of OSX. But clicking in the Finder closes the Gifox menu before you can even drag into it, so the feature isn't possible. Even clicking to choose from downloads folder doesn't work...

How can I upload my media?

**Comment by iby** [comment]
Hey @ColinRhoads! I'm doing some housekeeping and realized we never got back on this – my apologies, this is not a very good support… at all… 🤦‍♂️

I believe we started looking into this and discovered a bug, and then the release took awhile to see the light, and we completely lost track of this bug report. A lot of issues with file imports have been resolved and new features were added since then. Please give the latest 2.6.1 version a go if you haven't already.

P. S. There's a [GIF with documentation](https://gifox.app/docs/converting#importing-media) on how to import files. You should also be able to click on the drop-area, which opens a file selection dialog where you can select files for importing.

I'm going to resolve this, but please feel free to follow up on this. And, again, sorry for the late reply! 🙏
