### ISSUE TITLE
Transparency lost

### ISSUE THREAD

**Issue by raulriera** [Gifox/Tracker#249]
Hey everyone! unsure if this is related to the new macOS version (Monterey) , or a new regression in the app. But when recording gifs, the background is now white instead of the usual transparent.

<img src="https://user-images.githubusercontent.com/24159/191519401-75eaac54-5b59-4aa7-ba6b-077720a6180b.gif" width=350 />

(Download the above image for an example)

Cheers

**Comment by pankajparashar** [comment]
I confirm , I see the same issue on Desktop as well

**Comment by iby** [comment]
Hello friends. Apologies for the lagged reply, all of us are on a personal leave until the end of the month and are slow on responses.

We actually never supported transparency in exported GIFs because of what (and how) gets captured leaves very narrow usage for it – you can read about this in [this thread](https://github.com/Gifox/Tracker/issues/207#issuecomment-920275886).

Now that we support importing other formats, this can be useful. However, this won't solve this particular issue with shadows and I'm going to close this – again, see the mentioned thread for details.

P.S. If you're looking for a nice shadow on a GIF posted on a website, the best thing to do is add this via CSS and round the corners as well for a tidier look.

**Comment by raulriera** [comment]
Hmmmm not sure I understand, transparent was working (with or without shadows) what was the change that removed it?

**Comment by iby** [comment]
See the links. TL;DR: GIF format doesn't support transparency, it supports opacity. Transparent shadow pixels can be converted to opaque pixels and this conversion won't look good. This has been like that for the past 35 years since the GIF was invented and Gifox handles transparency exactly as it used to – draws it on the solid white color when shadow is enabled and desktop background is not.

**Comment by raulriera** [comment]
Thanks for the replay, I also read the other thread but you are mentioning that this has never been the case where in fact I have been using transparency on the recorded gifs (however the tool was actually accomplishing it before) for the last 3 years using both versions 2 and 3 of Gifox. I was just confused by the responses, but it does appear to be something that is no longer supported. 

Thanks again!

**Comment by iby** [comment]
@raulriera can we be talking about different things? Do you have an example GIF that you can share?

I assumed that you want the window shadow to be transparent, not on a white background?

![CleanShot 2022-10-06 at 11 47 24](https://user-images.githubusercontent.com/1086845/194294382-27b41358-0639-4ec0-a47b-cc01ee0c72d0.png)

If that's the case, then the above stands true. We never had this supported because this kind of transparency is not supported by the GIF format itself. This applies to all GIFs, literally, whether produced with Gifox or any other software. But you sound pretty certain, so I'm curious if we're talking about different things or if there's some other misunderstanding?

**Comment by raulriera** [comment]
Yeah I meant the white background (regardless of the shadow). But it turns out that:

- I no longer have access to my previous employees to see these GIFs
- For some reason chrome extensions are adding a little padding around Gifox which maybe is what made me notice this issue

I am probably just remembering all of these wrong and confusing between the normal macOS screen with (with shadows) and this tool...

Sorry for all the back and forward!
