### ISSUE TITLE
Selecting area too close to the edge of the screen hides controls

### ISSUE THREAD

**Issue by tir38** [gifox/tracker#271]
If I select area to record and that area is too close to the size of the screen, then there is no room for the pause/stop controls. So there is no way to stop the recording. The only way to stop is to force-quit Gifox.

**Comment by lerinagalimova** [comment]
Hey @tir38, thanks for reaching out!
This is the intentional behavior – when the selection menu cannot be accommodated on either side of the selection area, it moves inside the selection. During selection, the menu allows your to access quick configuration and start the recording. But during the recording it get's hidden to prevent obstructing interactions, when it's inside the selection area. In this case, yes, you end up with no selection menu on the screen, but you can still use shortcuts and the status bar menu:
1. By default, pressing Command + Escape stops the current recording, see [docs](https://gifox.app/docs/shortcuts) for further info.
2. During recording the status bar icon changes to "stop", which also stops the recording.

I'm going to close this down. Feel free to reopen or let me know if you have any other questions?

**Comment by tir38** [comment]
Great thanks. I see what was happening....

The stop button + the record timer is wider than the gifox icon itself. So when I start recording and the menu bar icon gets wider it becomes just wide enough to no longer fit in the menu bar. Because of the notch and other icons, the menu bar runs out of space and just hides gifox icon entirely.

I solved the problem by removing some other menu icons and also dragging the gifox icon to the right so that it's never the first one to be removed when there is limited space. Thanks!
