### ISSUE TITLE
doesn't reduce file size now matter how I edit it, seems to crash on export with no plausible cause. 

### ISSUE THREAD

**Issue by mpstaton** [gifox/tracker#272]
Hey, I've been trying to reduce the file size of a GIF recorded on Gifox for about 45 minutes now.  With irony, the reason is so I can post an example of an error to the Figma forum.  It won't take more than 4 megabytes.  

I have tried to use the "editor" included in Gifox many many times, changed the export settings down to a low frame rate per second, used the Blade to cut out large portions, tried to export it to a different file in case the naming collision was happening.  

I'm out of ideas.  Your GIF taker is awesome, your GIF editor just doesn't work as far as I can tell.  I'm fully up to date on all Mac software and your software.  Just for fun, let me see if I can attach the GIF that I have messed around with for the past forever.  

![Uploading 2024-02-06 19.59.19.gif…]()

**Comment by mpstaton** [comment]
![2024-02-06 19 59 19](https://github.com/Gifox/Tracker/assets/5722/95278e93-d437-42c3-b618-e54ae7472936)

**Comment by iby** [comment]
Hey @mpstaton! While I can help with some tricks on improving the GIF file size, before I go deeper into this, it would help a lot to see the logs. As per your other issue #273 – feels like this might be real problem why you're not seeing any change, for example, if there's a problem with the output folder and the GIF is not being exported there as expected, then it would explain why you're not seeing any changes. Trimming ends or cutting out a chunk should definitely produce an effect.

Generally, with the output folder, it's recommend to use a local folder, not Dropbox or Google Drive or anything cloud-connected. Also, to make sure you're [re-exporting the edited file](https://gifox.app/docs/exporting#exporting-1), you can try deleting the originally exported GIF, and after re-exporting it should re-appear in the same folder.

**Comment by mpstaton** [comment]
[App Logs.txt](https://github.com/Gifox/Tracker/files/14200546/App.Logs.txt)
[App Settings.txt](https://github.com/Gifox/Tracker/files/14200547/App.Settings.txt)
[System Info.txt](https://github.com/Gifox/Tracker/files/14200548/System.Info.txt)

You guys are super clever to build this in your app.  Engineers always ask for this stuff and I'm halfway technical and I'm like "do what?"  This is the first time it's been click, grab, done. 

Honestly I do have dropbox and iCloud and I have no idea what's syncing and not.  I did move the folders that I was sending screenshots and GIFs to into the user root folder. I'm going to see if I can add the directory info in images below:

<img width="418" alt="Screenshot 2024-02-07 at 1 22 25 PM" src="https://github.com/Gifox/Tracker/assets/5722/c493cf22-1d5f-48a7-8fdb-bcadf160f8e6">
<img width="420" alt="image" src="https://github.com/Gifox/Tracker/assets/5722/e95a3f71-08f4-4263-be86-becc104ed63b">
<img width="1022" alt="image" src="https://github.com/Gifox/Tracker/assets/5722/fb20005f-36e8-481d-8983-5e72434927c4">

**Comment by mpstaton** [comment]
I don't even know who "staff" are.  I'm assuming that's just randomly there?

**Comment by iby** [comment]
Ha, glad to hear that this simplicity works – that's definitely what we're aiming for! 😃

Thanks for sending these though. A couple of things…

You do seem to be using a Dropbox folder for your output location. While this should work, Dropbox app (like any other cloud syncing) will be constantly syncing files and if they get changed during that syncing, things can go wrong. Again, we've seen this issue in the past and it has been fixed from our side, but I would still keep this in mind and try exporting to a "fully local" folder, just to verify that the "3rd party syncing" isn't causing troubles.

I do see from the logs that it references different folders. My best guess about what's happening:
- You had an original output folder selected and the original GIF got exported there.
- Later you selected a different folder.
- When trying to edit the original GIF, the export **does** go into the newly selected folder, not original.
- You will end up with the original GIF in the original folder, and edited/re-exported GIF in the currently selected folder.
- This is intentional behaviour, perhaps not the most intuitive. This is done to ensure that files outside the selected folder won't get messed up by re-exports.

Generally, if you feel there's something odd going on, I would recommend relaunching the app and re-selecting the output folder – that should sort out any random or temporary glitches.

With all that in mind, please give it another go and let me know if the problem remains?

Also, you might find useful [this thread](https://github.com/Gifox/Tracker/issues/143) on file sizes and [this article](https://medium.com/gifox/mastering-high-quality-gifs-with-gifox-e08647cd5b3b) on mastering high quality GIFs article.

**Comment by iby** [comment]
@mpstaton can you please update to the latest 2.6.4 version and let me know if you're still running into this? If you do, can I kindly ask to resend the diagnostics data, please? 🙏

**Comment by iby** [comment]
I'm going to close this down. If you're still running into the issue or need any help, please feel free to re-open this! 👍
