### ISSUE TITLE
The license couldn't be activated

### ISSUE THREAD

**Issue by ilyachenko** [gifox/tracker#287]
I just bought a license but cannot activate it. I’m not experiencing any network problems, haven’t activated this license previously, and I’ve also restarted the computer.

MacOS: Sonoma 14.5
Gifox: 2.6.5

<img width="600" alt="image" src="https://github.com/user-attachments/assets/a46eb864-fa23-4b88-87dc-6fc19efb1d7f">

**Comment by iby** [comment]
Hey @ilyachenko, apologies for the bad start. I just double checked the activation with your actual license – all seem to be working at our end, so hopefully this is something easy to fix.

The very obvious, but please make sure the license is entered exactly as it appears in the email.

Activation issues **are** normally caused by a network error – the problem can be somewhere in the middle and not necessarily with your Mac. These problems are usually temporary and the quickest way to fix it is to try activating over a different network, e.g., you can try using a VPN or your mobile [personal hotspot](https://support.apple.com/en-gb/111785).

If that doesn't do the trick, could you please send us the diagnostics data to team@gifox.app and I'll have a closer look – can be done by contacting support or manually attached to an email:

![diagnostic-data-smaller](https://github.com/Gifox/Tracker/assets/1086845/056d41a5-ec1d-4310-9013-8e4a132ece3d)

**Comment by ilyachenko** [comment]
Thank you! The issue was caused by my firewall rules.
