### ISSUE TITLE
Output directory selection not saved

### ISSUE THREAD

**Issue by samwhale** [gifox/tracker#290]
Hi, love the product. I have the pro version and it's great but today I found it to be unusable.

Just today I tried using it, and it showed me this screen

![image](https://github.com/user-attachments/assets/2bc2d674-bbd0-4775-9918-2a44b1b64ce9)

Selecting my downloads directory will close it. But then attempting to use it ends up going through the same cycle. I re-downloaded it from the app store on macosx but that didn't help, either.

Diagnostic data:
- [System Info.txt](https://github.com/user-attachments/files/17749859/System.Info.txt)
- [App Settings.txt](https://github.com/user-attachments/files/17749858/App.Settings.txt)
- [App Logs.txt](https://github.com/user-attachments/files/17749857/App.Logs.txt)

**Comment by iby** [comment]
Hey @samwhale thanks for the compliments! 🙏

There's a bug in earlier versions of macOS 15 Sequoia – if you can update to the latest 15.1, please do, otherwise see https://github.com/Gifox/Tracker/issues/286#issuecomment-2409004897 for details and workarounds.

I just closed that issue yesterday – probably was a little too quick on that. Gonna pin it to the top. Will close this as a duplicate, but please feel free to comment or leave more feedback.

**Comment by samwhale** [comment]
thanks for the quick response. I'll check that out, thank you
