### ISSUE TITLE
Add fullscreen option?

### ISSUE THREAD

**Issue by danielbayley** [Gifox/Tracker#38]
This is easily the best little GIF utility Iv'e come across. 👏 

But how about a third, fullscreen option? (Maybe with an accompanying little icon in the UI next to the existing 2…)

**Comment by ianbytchek** [comment]
Good idea, thanks for suggesting :thumbsup: At the moment we still have a few issues with compression and especially large gif playback #28. I'll backlog this for now, but very positive on implementing.

**Comment by ianbytchek** [comment]
In a recent update you get access to <kbd>Cmd</kbd> + <kbd>A</kbd> shortcut, which selects entire screen. We're still considering adding an actual button for that.

**Comment by ianbytchek** [comment]
After 3 years it became apparent that nothing good can possibly come out when you try to record a full screen GIF.

Most GIFs that can be found on the web are relatively small and well optimized. That is because in 99.9% cases the whole purpose of a GIF is to quickly and accessibly share a motion graphic via the Internet. This implies that the file size also should be reasonable, which grows pretty much exponentially with image size. Add here retina display and this value will quadruple.

Quite a few users who start using the app don't know a lot about how GIF format works and try to record pretty much the entire screen simply because that's what they used to do for screenshots. A very typical reaction is to get upset about 30 MB file size being too much for an animated screenshot and taking 5 minutes to compress…

The irony is once you get familiar with the format and learn to balance between image quality vs. file size you'd rarely need full-screen recording. At the same time, starting your experience with creating unusable GIFs makes no one happy. For that reason we won't be adding a separate button for new users shooting themselves in the foot, but will leave the shortcut for those familiar with the app and knowing what they're doing. ✌️
