### ISSUE TITLE
Add granular gif compression configuration

### ISSUE THREAD

**Issue by ianbytchek** [gifox/tracker#5]
Gifox in general is optimised for better quality over size, this is a nice thing, but with complex images containing many details and colours final file size gets way too large – not cool.

**Comment by maxhoffmann** [comment]
Yes! Just bought the app and it does pretty much what I want. The quality is not great though, the colours are off and it would be great if this could be changed in the settings.

**Comment by ianbytchek** [comment]
Planned for this summer :thumbsup:

**Comment by dimitrieh** [comment]
I would love an "expert controls panel" user interface which you can adjust before it actually begins recording. This mainly for colors as this impacts quality the most. Say I have a scene which I know only has 2-3 colors, I want to be able to select that prior to recording in order to wind up with a small usable gif. (make it a toggle in the settings to show "expert GUI")

quick example:

![gifox](https://cloud.githubusercontent.com/assets/429659/17941907/890a7330-6a35-11e6-936d-79077546197e.png)

**Comment by ianbytchek** [comment]
@dimitrieh you are spot-on, this is exactly what we have in mind plus extra recording settings and other compression configuration once its ready.

**Comment by dimitrieh** [comment]
@ianbytchek got ya :D cant wait and good luck ^^

**Comment by ianbytchek** [comment]
Coming up in a couple of days! :bowtie:
