### ISSUE TITLE
Countdown timer to allow preparation

### ISSUE THREAD

**Issue by jchlu** [gifox/tracker#70]
It would be super useful to have time to prepare before recording starts - 
a typical use case for this would be clicking a modal to gauge recording size, but wanting the "click" to be recorded at the start.
Example - to demonstrate UK travel info now available in the Maps app:
Select the area to be recorded:

![Modal Selection Area](http://d.jch.lu/USzEPA/1O7wceOU+)

*then* click away, to be able to have the modal appear during recording, but not be there at the start:

![Without modal](http://d.jch.lu/2HhmJz/Oe62erq8+)

*then* start recording. (This is kind of tricky without a pause / countdown) and results in the modal appearing until you change focus:

![Gifox Recording](http://d.jch.lu/AbefK3/36vYdPwL+)

Johnny.

**Comment by ianbytchek** [comment]
@jchlu looked further into this. The reason it happens is because Gifox steals focus, unlike screencapture app, which might affect other apps. This is what we should and will prioritise on, as timer would be a workaround, not a solution.

☝️ However, v1.5.0 just came right out of oven with reworked selection and better shortcut support. Here's what you can do:

1. Open up maps, get it into necessary state.
2. <kbd>⌘ Cmd</kbd> + <kbd>⇧ Shift</kbd> + <kbd>6</kbd> to open window selection mode and select maps.
3. <kbd>⌘ Cmd</kbd> + <kbd>⇧ Shift</kbd> + <kbd>5</kbd> to switch into area mode preserving window selection.
4. <kbd>Space</kbd> to start recording and <kbd>⌘ Cmd</kbd> + <kbd>Esc</kbd> to stop.

Looks like this + result below:

![maps](https://user-images.githubusercontent.com/1086845/34452480-16202848-ed5a-11e7-9247-a7f1ab5f1c25.gif)

![2017-12-30 11 54 38](https://user-images.githubusercontent.com/1086845/34452482-26937586-ed5a-11e7-914f-1c97354d7061.gif)
