### ISSUE TITLE
CLI Utility of the Selector Mechanism

### ISSUE THREAD

**Issue by crydalch** [Gifox/Tracker#78]
Gifox's selector mechanism is excellent; would it be possible to embed a command-line tool for the selector? On Linux, utilities like [slop](https://github.com/naelstrof/slop) allow the user to draw a region on screen space, and print out the position/dimensions to the shell, where they can be used by other tools or scripts.

It'd be great to have it ride inside of Gifox's app package. One example is taking timed selection screenshots with the mouse cursor (this isn't possible with Screencapture); a tool like this could pass the rectangle to Screencapture or some other screenshot tool.

And it'd be great to control the print out in the same way as slop; with %x, %y, etc... we could format the output as needed.

Thanks!

**Comment by iby** [comment]
I'm doing some housekeeping and going to close this issue – with the existing backlog of fixes and improvements this would be a big distraction and won't serve the interests of the majority of our users, sorry.

That said, I remember looking into this awhile ago when we discussed this. It turned out to be trickier than initially anticipated – this feature requires creating a completely new logic workflow that will need to be tested and maintained.

We would be happy to reopen and reconsider this feature request if it gains appropriate attention! 🙏
