### ISSUE TITLE
Gifox crashes on launch, missing SwiftyJSON

### ISSUE THREAD

**Issue by whymarrh** [Gifox/Tracker#96]
(I think this is new to 1.6.1 but I'm only noticing it now.)

Gifox won't start, it crashes on launch. I've attached a crash log.

This is also in the crash file but I'm running:

macOS High Sierra
Version 10.13.6

[`Gifox_2018-08-02-111410.crash`](https://github.com/gifox/tracker/files/2253733/Gifox_2018-08-02-111410.crash.txt)

**Comment by ianbytchek** [comment]
Hmmm, this seems to happen a little more often than I thought. This problem occurs on case sensitive filing systems and will be fixed in the next release. We've messed up a little and used the wrong case for naming one of the frameworks… 🤦‍♂️ For now please rename it with the following terminal command:

```sh
mv /Applications/Gifox.app/Contents/Frameworks/SwiftyJson.framework /Applications/Gifox.app/Contents/Frameworks/SwiftyJSON.framework
```

After that Gifox might occasionally complain that it's damaged, in which case try re-downloading and doing the same, until we release the update.

**Comment by whymarrh** [comment]
Cool, thanks! I look forward to the update!

**Comment by patobiskoto** [comment]
Oh I have the same issue with the latest version. 
Any news please?

**Comment by ianbytchek** [comment]
We had a few setbacks with the next major update but it's planned for the near future – it covers this issue and brings new awesome features. Hold on a little more!

**Comment by mateusmedeiros** [comment]
Here an "open -a Gifox" returned the following error:

```bash
LSOpenURLsWithRole() failed for the application /Applications/Gifox.app with error -10810
``` 

 and I couldn't find any mention whatsoever of that error associated with Gifox on google (which now kinda makes sense since apparently nobody cares about turning on case sensitivity on macs).

While searching just for that error, I found stuff about Gatekeeper, com.apple.quarantine xattrs, execution permission on the binary and so on, so I kept thinking that I had messed something up 😅

Only after having the idea (really don't know why I didn't had it earlier) of running the binary directly I found a "dyld: Library not loaded" error, which eventually led me into this issue, but by then I had lost several hours, haha.

So since it's almost one year old and it's somewhat past the "near future" of oct/2018, just checking if this is still on you guys' radar. Is there any news?

**Comment by ianbytchek** [comment]
@mateusmedeiros it 100% is! We hoped for the quick turnaround with version 2, but it's still in the beta, where this is fixed. The fix is also available [above](https://github.com/Gifox/Tracker/issues/96#issuecomment-409961653), alternatively feel free to give beta a go, though there's another [issue and fix](https://github.com/Gifox/Tracker/issues/108#issuecomment-500960163) atm… 😣

**Comment by mateusmedeiros** [comment]
@ianbytchek Yeah, the workaround worked great, thanks!
I'm testing the beta right now, will make sure to open an issue if anything bad happens 😁

**Comment by whymarrh** [comment]
Gifox 2 is out and works well for me! Thanks @ianbytchek!

**Comment by ianbytchek** [comment]
Yes, apologies for the huge delay guys. It was meant to come out way earlier, but you probably know better than me how these things go. There're a couple of issues with the latest release if you're using the direct-download version try enabling pre-releases and using the beta – it's always two steps ahead.
